// Add more sample posts for demonstration purposes.
const posts = [
  {
    title: "Java 21 makes me like Java again",
    url: "https://github.com/openjdk/jdk",
    points: 100,
    user: "user1",
    time: "1 hour",
  },
  {
    title: "Why Python is awesome",
    url: "https://github.com/python/cpython",
    points: 50,
    user: "user2",
    time: "2 hours",
  },
  {
    title: "Exploring Rust for Web Development",
    url: "https://github.com/rust-lang/rust",
    points: 70,
    user: "user3",
    time: "3 hours",
  },
  {
    title: "TypeScript: The future of JavaScript?",
    url: "https://github.com/microsoft/TypeScript",
    points: 85,
    user: "user4",
    time: "4 hours",
  },
  {
    title: "React vs Vue: Battle of the front-end",
    url: "https://github.com/facebook/react",
    points: 95,
    user: "user5",
    time: "5 hours",
  },
  {
    title: "Machine Learning with TensorFlow 2.0",
    url: "https://github.com/tensorflow/tensorflow",
    points: 110,
    user: "user6",
    time: "6 hours",
  },
  {
    title: "Deep Dive into Kubernetes Networking",
    url: "https://github.com/kubernetes/kubernetes",
    points: 120,
    user: "user7",
    time: "7 hours",
  },
  {
    title: "The Power of Functional Programming with Haskell",
    url: "https://github.com/ghc/ghc",
    points: 90,
    user: "user8",
    time: "8 hours",
  },
  {
    title: "The Rise of Deno: Is it the next Node.js?",
    url: "https://github.com/denoland/deno",
    points: 80,
    user: "user9",
    time: "9 hours",
  },
  {
    title: "GraphQL vs REST: Which one to choose?",
    url: "https://github.com/graphql/graphql-js",
    points: 100,
    user: "user10",
    time: "10 hours",
  },
  {
    title: "Introduction to WebAssembly",
    url: "https://github.com/WebAssembly/design",
    points: 88,
    user: "user11",
    time: "11 hours",
  },
  {
    title: "The elegance of Elixir Programming",
    url: "https://github.com/elixir-lang/elixir",
    points: 72,
    user: "user12",
    time: "12 hours",
  },
  {
    title: "Modern CSS with Flexbox and Grid",
    url: "https://github.com/w3c/csswg-drafts",
    points: 65,
    user: "user13",
    time: "13 hours",
  },
  {
    title: "Why PWA is the future of web apps?",
    url: "https://developers.google.com/web/progressive-web-apps",
    points: 105,
    user: "user14",
    time: "14 hours",
  },
  {
    title: "Redis: Why it's more than just caching",
    url: "https://github.com/redis/redis",
    points: 115,
    user: "user15",
    time: "15 hours",
  },
];

export default posts;
